name: Build, Push to ACR and Deploy

on:
  push:
    branches:
      - master # 当推送到 master 分支时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push to ACR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Alibaba Cloud ACR
        run: |
          docker login crpi-4lb4yrqwonqicstn.cn-beijing.personal.cr.aliyuncs.com \
            -u ${{ secrets.ALIYUN_ACR_USERNAME }} \
            --password-stdin <<< "${{ secrets.ALIYUN_ACR_PASSWORD }}"

      - name: Build the Docker image
        run: |
          docker build . -t crpi-4lb4yrqwonqicstn.cn-beijing.personal.cr.aliyuncs.com/lshbosheth/bosheth-archiver:${{ github.sha }}

      - name: Tag as latest
        run: |
          docker tag crpi-4lb4yrqwonqicstn.cn-beijing.personal.cr.aliyuncs.com/lshbosheth/bosheth-archiver:${{ github.sha }} \
                crpi-4lb4yrqwonqicstn.cn-beijing.personal.cr.aliyuncs.com/lshbosheth/bosheth-archiver:latest

      - name: Push to ACR
        run: |
          docker push crpi-4lb4yrqwonqicstn.cn-beijing.personal.cr.aliyuncs.com/lshbosheth/bosheth-archiver:${{ github.sha }}
          docker push crpi-4lb4yrqwonqicstn.cn-beijing.personal.cr.aliyuncs.com/lshbosheth/bosheth-archiver:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    name: Deploy to Server via SSH

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # 登录阿里云 ACR
            echo "${{ secrets.ALIYUN_ACR_PASSWORD }}" | docker login crpi-4lb4yrqwonqicstn.cn-beijing.personal.cr.aliyuncs.com -u ${{ secrets.ALIYUN_ACR_USERNAME }} --password-stdin

            # 拉取最新镜像
            docker pull crpi-4lb4yrqwonqicstn.cn-beijing.personal.cr.aliyuncs.com/lshbosheth/bosheth-archiver:${{ github.sha }}

            # 停止并删除旧容器
            docker stop bosheth-archiver || true
            docker rm bosheth-archiver || true

            # 启动新容器
            docker run -d \
              --name bosheth-archiver \
              -p 1222:3000 \
              crpi-4lb4yrqwonqicstn.cn-beijing.personal.cr.aliyuncs.com/lshbosheth/bosheth-archiver:${{ github.sha }}
